In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split  
from sklearn.linear_model import LinearRegression 

In [2]:
data=pd.read_csv('http://bit.ly/w-data')

In [4]:
data.head(2)

Hours  Scores
0    2.5      21
1    5.1      47

In [7]:
features=['Hours']
target=['Scores']


In [31]:
X=data[features].values
y=data[target].values

In [44]:
X_Train, X_Test, y_Train, y_test=train_test_split(X, y, random_state=0, train_size=0.75)

In [45]:
reg = LinearRegression()
reg.fit(X_Train, y_Train)

LinearRegression()

In [48]:
prediction=reg.predict([[1.5]])

In [49]:
prediction

array([[16.84472176]])

In [50]:
pre=reg.predict(X_Test)

In [51]:
pre

array([[16.84472176],
       [33.74557494],
       [75.50062397],
       [26.7864001 ],
       [60.58810646],
       [39.71058194],
       [20.8213931 ]])

In [52]:
X_Test

array([[1.5],
       [3.2],
       [7.4],
       [2.5],
       [5.9],
       [3.8],
       [1.9]])

In [53]:
import pandas as df
import numpy as pn
from sklearn import tree
from sklearn.model_selection import train_test_split  

In [57]:
data=df.read_csv('C:/Users/a/Downloads/Iris.csv')

In [58]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [69]:
features=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm' ]
targets=['Species']

In [70]:
X=data[features].values
y=data[targets].values

In [71]:
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=0, train_size=.80)

In [72]:
tr= tree.DecisionTreeClassifier()
tr.fit(X_train, y_train)

DecisionTreeClassifier()

In [76]:
pre=tr.predict([[ 5.9, 3.0, 5.1, 2.3]])

In [77]:
pre

array(['Iris-virginica'], dtype=object)